services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: langchain-template-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true

  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: langchain-template-prod
    ports:
      - "8000:8000"
    env_file:
      - .env
